version: "3.1"
services:

  backend-server:
    build: .
    restart: always
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    networks:
      - backend
    depends_on:
      - postgres
    environment:
      CONSOLE_LOG: "true"
      PORT: ${PORT}
      LOG_LEVEL: 3

  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_BASE}
    ports:
      - 5432:5432
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    name: backend-network
